# 语言代码
languageCode = "zh-cn"
# 语言的名称
languageName = "简体中文"
# 语言权重顺序
weight = 1

# 网页标题
title = "Sizeskong Blog"

# 语言在网站中的展示名
[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

# 作者信息
[author]
  name = "Sizeskong"
  image = "img/avatar.jpg"
  #headline = "一个强大、轻量级的 Hugo 主题。"
  #bio = "一个强大、轻量级的 Hugo 主题。"
  #links = [
  #  { x-twitter = "https://twitter.com/burufugu" },
  #  { github = "https://github.com/sizeskong" },
  #]
